# Site settings
title: al
email: andreloureiroo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Front End Developer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrel.me" # the base hostname & protocol for your site
twitter_username: spigones
github_username:  andreloureiro

# Build settings
markdown: kramdown
